misc:
  - branch: &BRANCHES
      #  In this pull request, the changes are based on the main branch
      - &MASTER_BRANCH base=main

pull_request_rules:
  - name: Blocking PR if missing a related issue
    conditions:
      # branch condition: in this pull request, the changes are based on any branch referenced by BRANCHES
      - or: *BRANCHES
      - and:
          - -body~=\#[0-9]{1,6}(\s+|$)
          - -body~=https://github.com/milvus-io/milvus/issues/[0-9]{1,6}(\s+|$)
      - or:
        - label=kind/enhancement
        - label=kind/bug
        - label=kind/feature          
    actions:
      label:
        add:
          - do-not-merge/missing-related-issue
      comment:
        message: |
          @{{author}} Please associate the related issue to the body of your Pull Request.  (eg. “issue: #<xyz>”)

  - name: Dismiss block label if related issue be added into PR
    conditions:
      - and:
          # branch condition: in this pull request, the changes are based on any branch referenced by BRANCHES
          - or: *BRANCHES
          - or:
              - body~=\#[0-9]{1,6}(\s+|$)
              - body~=https://github.com/milvus-io/milvus/issues/[0-9]{1,6}(\s+|$)
    actions:
      label:
        remove:
          - do-not-merge/missing-related-issue
          
  - name: Label bug fix PRs
    conditions:
      # branch condition: in this pull request, the changes are based on any branch referenced by BRANCHES
      - or: *BRANCHES
      - 'title~=^fix:'
    actions:
      label:
        add:
          - kind/bug

  - name: Label feature PRs
    conditions:
      # branch condition: in this pull request, the changes are based on any branch referenced by BRANCHES
      - or: *BRANCHES
      - 'title~=^feat:'
    actions:
      label:
        add:
          - kind/feature
  
  - name: Label enhancement PRs
    conditions:
      # branch condition: in this pull request, the changes are based on any branch referenced by BRANCHES
      - or: *BRANCHES
      - 'title~=^enhance:'
    actions:
      label:
        add:
          - kind/enhancement
